create table if not exists public.watchlist (
  id bigint generated by default as identity primary key,
  symbol text not null unique,
  note text,
  created_at timestamptz not null default now()
);

alter table public.watchlist enable row level security;

create policy "watchlist_select_all"
on public.watchlist
for select
using (true);

create policy "watchlist_insert_all"
on public.watchlist
for insert
with check (true);

grant select, insert on public.watchlist to anon, authenticated;
grant usage, select on sequence public.watchlist_id_seq to anon, authenticated;
