import { bollinger, detectPattern, ema, macd, rsi, sma, supportResistance, volumeSignal } from "./indicators";
import type { AnalysisResult, Candle, Fundamentals, NewsItem, TechnicalSignal, Timeframe } from "./types";

export async function buildAnalysis(input: { symbol: string; companyName: string; currency: string; timeframe: Timeframe; candles: Candle[]; fundamentals: Fundamentals; news: NewsItem[] }): Promise<AnalysisResult> {
  const closes = input.candles.map(c => c.close); const price = closes.at(-1) ?? 0; const ma20 = last(sma(closes, 20)); const ma50 = last(sma(closes, 50)); const ema21 = last(ema(closes, 21)); const r = rsi(closes); const m = macd(closes); const bands = bollinger(closes); const sr = supportResistance(input.candles); const vol = volumeSignal(input.candles); const pattern = detectPattern(input.candles);
  const trend = price > (ma20 ?? price) && price > (ma50 ?? price) ? "Bullish" : price < (ma20 ?? price) && price < (ma50 ?? price) ? "Bearish" : "Sideways";
  const technicalSignals: TechnicalSignal[] = [
    sig("Trend", trend, trend === "Bullish" ? "positive" : trend === "Bearish" ? "negative" : "neutral", "Compares price with moving averages."),
    sig("EMA 21", fmt(ema21), price > (ema21 ?? price) ? "positive" : "negative", "Short-term trend reference."),
    sig("RSI", r.toFixed(1), r < 30 ? "positive" : r > 70 ? "warning" : "neutral", "Overbought and oversold momentum gauge."),
    sig("MACD", m.histogram >= 0 ? "Bullish momentum" : "Bearish momentum", m.histogram >= 0 ? "positive" : "negative", "Fast-vs-slow momentum signal."),
    sig("Bollinger Bands", price > bands.upper ? "Above upper band" : price < bands.lower ? "Below lower band" : "Inside bands", price > bands.upper ? "warning" : price < bands.lower ? "positive" : "neutral", "Shows whether price is stretched."),
    sig("Volume", `${vol.ratio.toFixed(2)}x average`, vol.ratio > 1.4 ? "positive" : vol.ratio < .65 ? "warning" : "neutral", "High volume confirms participation."),
    sig("Support / Resistance", `${fmt(sr.support)} / ${fmt(sr.resistance)}`, price > sr.resistance ? "positive" : price < sr.support ? "negative" : "neutral", "Breakouts above resistance are bullish; breaks below support are bearish."),
    sig("Candlestick", pattern, pattern.includes("Bullish") ? "positive" : pattern.includes("Bearish") ? "negative" : "neutral", "Recent candle behavior.")
  ];
  const technicalScore = clamp(50 + (trend === "Bullish" ? 18 : trend === "Bearish" ? -18 : 0) + (m.histogram > 0 ? 10 : -10) + (r < 30 ? 8 : r > 75 ? -8 : 2) + (vol.ratio > 1.3 ? 6 : 0), 0, 100);
  const fundamentalScore = scoreFundamentals(input.fundamentals); const valuation = estimateValue(price, input.fundamentals); const valuationScore = clamp(50 + valuation.upsideDownside * .8 - (valuation.riskLevel === "High" ? 12 : 0), 0, 100); const newsScore = scoreNews(input.news);
  const totalScore = Math.round(technicalScore * .32 + fundamentalScore * .28 + valuationScore * .25 + newsScore * .15); const recommendation = recommend(totalScore, valuation.upsideDownside, valuation.riskLevel, trend);
  const strategy = { entryArea: `${fmt(Math.max(sr.support, price * .97))} - ${fmt(Math.min(price * 1.02, sr.resistance || price * 1.05))}`, stopLoss: fmt(Math.min(sr.support * .97, price * .92)), takeProfit1: fmt(Math.max(sr.resistance, price * 1.08)), takeProfit2: fmt(Math.max(valuation.optimisticTarget, price * 1.16)), bestTimeframe: trend === "Bullish" ? "Swing trade 2-8 weeks or position trade 3-12 months" : "Wait for confirmation on daily and weekly candles", riskLevel: valuation.riskLevel, positionSizing: valuation.riskLevel === "High" ? "Small size, 1-3% of portfolio" : valuation.riskLevel === "Medium" ? "Moderate size, 3-6% of portfolio" : "Normal size, 5-10% of portfolio", invalidation: `Setup weakens if price closes below ${fmt(sr.support)} with high selling volume.` };
  return { symbol: input.symbol.toUpperCase(), companyName: input.companyName, currency: input.currency, timeframe: input.timeframe, candles: input.candles, technicalScore: Math.round(technicalScore), fundamentalScore: Math.round(fundamentalScore), newsScore: Math.round(newsScore), valuationScore: Math.round(valuationScore), totalScore, marketTrend: trend, recommendation, aiSummary: await explain({ symbol: input.symbol, companyName: input.companyName, recommendation, totalScore, trend, upside: valuation.upsideDownside, risk: valuation.riskLevel }), technicalSignals, fundamentals: input.fundamentals, valuation, news: input.news, strategy, warnings: ["This analysis depends on available data quality and may be delayed.", "Always define invalidation before entering a position."] };
}

function scoreFundamentals(f: Fundamentals) { let s = 50; if ((f.revenueGrowth ?? 0) > 10) s += 12; if ((f.profitGrowth ?? 0) > 10) s += 12; if ((f.roe ?? 0) > 15) s += 12; if ((f.der ?? 999) < 100) s += 8; if ((f.cashFlow ?? 0) > 0) s += 8; if ((f.per ?? 999) > 45) s -= 8; if ((f.der ?? 0) > 200) s -= 14; if (f.revenue === null && f.eps === null) s -= 12; return clamp(s, 0, 100); }
function estimateValue(price: number, f: Fundamentals) { const methods = []; if (f.eps && f.eps > 0) methods.push({ name: "PER valuation", value: f.eps * ((f.per ?? 20) > 35 ? 24 : 18), explanation: "EPS multiplied by a target PE." }); if (f.pbv && f.pbv > 0) methods.push({ name: "PBV valuation", value: price / f.pbv * 2.5, explanation: "Book value per share times normalized PBV." }); methods.push({ name: "Historical momentum value", value: price * 1.08, explanation: "Recent trend reference when statements are incomplete." }); const fairValue = methods.reduce((s, x) => s + x.value, 0) / methods.length; const upsideDownside = (fairValue - price) / price * 100; const riskLevel = Math.abs(upsideDownside) > 35 || !f.eps || (f.der ?? 0) > 180 ? "High" : Math.abs(upsideDownside) > 18 ? "Medium" : "Low"; return { currentPrice: price, fairValue, upsideDownside, conservativeTarget: fairValue * .9, optimisticTarget: fairValue * 1.15, riskLevel, methods }; }
function scoreNews(news: NewsItem[]) { return clamp(news.reduce((s, n) => s + (n.sentiment === "positive" ? 8 : n.sentiment === "negative" ? -8 : 0), 50), 0, 100); }
function recommend(score: number, upside: number, risk: string, trend: string): AnalysisResult["recommendation"] { if (score >= 72 && upside > 12 && risk !== "High" && trend !== "Bearish") return "Buy"; if (score >= 62 && upside > 5) return "Watchlist"; if (score >= 48) return "Hold"; if (score >= 38) return "Sell"; return "Avoid"; }
async function explain(p: Record<string, string | number>) { const base = `${p.companyName} (${p.symbol}) is rated ${p.recommendation} with score ${p.totalScore}/100. Trend is ${p.trend}, estimated upside is ${Number(p.upside).toFixed(1)}%, and risk is ${p.risk}. This is educational analysis, not financial advice.`; if (!process.env.OPENAI_API_KEY) return base; try { const r = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { Authorization: `Bearer ${process.env.OPENAI_API_KEY}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: process.env.OPENAI_MODEL || "gpt-4.1-mini", input: `Explain for beginners with risk and invalidation: ${JSON.stringify(p)}`, max_output_tokens: 180 }) }); const j = await r.json(); return j.output_text || base; } catch { return base; } }
function sig(label: string, value: string, tone: TechnicalSignal["tone"], explanation: string): TechnicalSignal { return { label, value, tone, explanation }; }
function last(values: Array<number | null>) { return values.filter((v): v is number => v !== null).at(-1) ?? null; }
function clamp(v: number, min: number, max: number) { return Math.max(min, Math.min(max, v)); }
function fmt(v: number | null | undefined) { return typeof v === "number" && Number.isFinite(v) ? v.toFixed(2) : "-"; }
